name: Send Discovered API to ApiConnect 

on: [pull_request, workflow_dispatch, push]

env:
  API_HOST: us-east-a.apiconnect.automation.ibm.com
  PROVIDER_ORG: api-connect-fo-0
  API_FILES: APIfolder/photos.yaml
  #API_FILES: APIfolder/uber-api.json
  #API_FILES: APIfolder/coffee-store.yaml
  #API_FOLDERS: APIfolder,APIfolderTwo

jobs:
  run-discovery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Difference
      id: difference-output
      run: |
        echo "action_updates=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
    - uses: ibm-apiconnect/apic-discovery-action@main 
      id: discover-apis
      with:
        api_host: tj-isa-1-420eb34f056ae68f3969289d61f61851-0000.jp-tok.containers.appdomain.cloud
        platform_api_prefix: api-manage-1720ed5d-api-manager-tech-jam-apic
        INSECURE_SKIP_TLS_VERIFY: true
        provider_org: tech-jam-09
        api_key: ${{ secrets.apicApikey_participant_12 }}
        api_files: APIfolder/photos.yaml
        #api_folders: ${{ env.API_FOLDERS }}
        resync_check: ${{ true }}
        insecure_skip_tls_verify: ${{ env.INSECURE_SKIP_TLS_VERIFY }}
        git_diff: ${{ steps.difference-output.outputs.action_updates }}
    - name: Display the action-result
      run: |
        echo "Result of the action: ${{ steps.discover-apis.outputs.action-result }}"
        echo "End"  
